import type { IconType } from '@/components/icons';
import type { NavItem } from '@/types';

export const platformNavItems: NavItem[] = [
  // ── Platform mode ──────────────────────────────────────────────────────────
  // The daily destinations stay at the top level; everything a staff member
  // visits occasionally lives one click deeper, inside a group.
  {
    title: 'Platform Overview',
    href: '/platform',
    icon: 'dashboard' as IconType,
    label: 'platformOverview',
    roles: ['PLATFORM_OWNER', 'ADMIN', 'FINANCE', 'SUPPORT'],
    scope: 'platform',
  },
  {
    title: 'Academies',
    href: '/academies',
    icon: 'store' as IconType,
    label: 'allAcademies',
    roles: ['PLATFORM_OWNER', 'ADMIN', 'FINANCE', 'SUPPORT'],
    scope: 'platform',
  },
  {
    title: 'Users',
    href: '/platform/users',
    icon: 'users' as IconType,
    label: 'users',
    roles: ['PLATFORM_OWNER', 'ADMIN', 'SUPPORT'],
    scope: 'platform',
  },
  {
    title: 'Support Inbox',
    href: '/support',
    icon: 'help' as IconType,
    label: 'supportInbox',
    roles: ['PLATFORM_OWNER', 'ADMIN', 'SUPPORT'],
    supportOnly: true,
    scope: 'platform',
  },
  // Money — platform cash in (managers → Mentoma) and cash out
  {
    title: 'Platform Money',
    icon: 'dollarSign' as IconType,
    label: 'platformFinanceHub',
    roles: ['PLATFORM_OWNER', 'ADMIN', 'FINANCE'],
    scope: 'platform',
    children: [
      {
        title: 'Investor Report',
        href: '/platform/metrics',
        icon: 'trendingUp' as IconType,
        label: 'investorReport',
        roles: ['PLATFORM_OWNER', 'ADMIN', 'FINANCE'],
        scope: 'platform',
      },
      {
        title: 'Platform costs',
        href: '/platform/costs',
        icon: 'dollarSign' as IconType,
        label: 'platformCosts',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Financial',
        href: '/financial/desk',
        icon: 'dollarSign' as IconType,
        label: 'financialDesk',
        roles: ['PLATFORM_OWNER', 'ADMIN', 'FINANCE'],
        financeOnly: true,
        scope: 'platform',
        paymentGated: true,
      },
      {
        title: 'Platform Vouchers',
        href: '/coupons',
        icon: 'percent' as IconType,
        label: 'platformVouchers',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Withdrawals',
        href: '/withdrawals',
        icon: 'banknote' as IconType,
        label: 'withdrawals',
        roles: ['PLATFORM_OWNER', 'ADMIN', 'FINANCE'],
        financeOnly: true,
        scope: 'platform',
        paymentGated: true,
      },
      {
        title: 'Teacher Payouts',
        href: '/teacher-payouts',
        icon: 'wallet2' as IconType,
        label: 'teacherPayouts',
        roles: ['PLATFORM_OWNER', 'ADMIN', 'FINANCE'],
        financeOnly: true,
        adminOnly: true,
        scope: 'platform',
        paymentGated: true,
      },
    ],
  },
  // Content — what the platform publishes, and the templates academies start from
  {
    title: 'Content & Templates',
    icon: 'gallery' as IconType,
    label: 'contentHub',
    roles: ['PLATFORM_OWNER', 'ADMIN'],
    scope: 'platform',
    children: [
      {
        title: 'Platform Blog',
        href: '/platform/blog',
        icon: 'fileText' as IconType,
        label: 'platformBlog',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Broadcasts',
        href: '/platform/broadcasts',
        icon: 'megaphone' as IconType,
        label: 'broadcasts',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Dashboard Banners',
        href: '/platform/dashboard-banners',
        icon: 'image' as IconType,
        label: 'dashboardBanners',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Storage',
        href: '/platform/storage',
        icon: 'hardDrive' as IconType,
        label: 'platformStorage',
        roles: ['PLATFORM_OWNER'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Templates Gallery',
        href: '/website/appearance/list',
        icon: 'gallery' as IconType,
        label: 'templatesGallery',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Template Covers',
        href: '/settings/template-covers',
        icon: 'media' as IconType,
        label: 'templateCovers',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
    ],
  },
  // Configuration — what the platform sells
  {
    title: 'Configuration',
    icon: 'settings' as IconType,
    label: 'configurationHub',
    roles: ['PLATFORM_OWNER', 'ADMIN'],
    scope: 'platform',
    children: [
      {
        title: 'Platform Settings',
        href: '/platform-settings',
        icon: 'settings' as IconType,
        label: 'platformSettings',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Plan Pricing',
        href: '/platform/pricing',
        icon: 'layers' as IconType,
        label: 'planPricing',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
    ],
  },
  // Governance — trust, legal and audit surfaces
  {
    title: 'Trust & Legal',
    icon: 'shield' as IconType,
    label: 'governanceHub',
    roles: ['PLATFORM_OWNER', 'ADMIN', 'SUPPORT'],
    scope: 'platform',
    children: [
      {
        title: 'Content Review',
        href: '/platform/moderation',
        icon: 'shield' as IconType,
        label: 'contentReview',
        roles: ['PLATFORM_OWNER', 'ADMIN', 'SUPPORT'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Legal Documents',
        href: '/platform/legal',
        icon: 'fileText' as IconType,
        label: 'legalDocuments',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Support Access Logs',
        href: '/support-access-logs',
        icon: 'shield' as IconType,
        label: 'supportAccessLogs',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
      {
        title: 'Roles & Permissions',
        href: '/platform/roles',
        icon: 'shield' as IconType,
        label: 'rolesPermissions',
        roles: ['PLATFORM_OWNER', 'ADMIN'],
        adminOnly: true,
        scope: 'platform',
      },
    ],
  },
];
