'use client';

import type { LiveSession } from '@/types/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { NumberInput } from '@/components/ui/number-input';
import { Label } from '@/components/ui/label';
import { DatePicker } from '@/components/ui/date-picker';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from '@/components/ui/card';
import { useTranslation } from '@/lib/i18n/hooks';
import { Video, Copy, RefreshCw } from 'lucide-react';
import { toast } from 'react-toastify';
import LiveSessionRecurrence from './LiveSessionRecurrence';
import { defaultTimezone, useLiveSessionForm } from './use-live-session-form';

type Props = {
  lessonId: string;
  initial?: LiveSession | null;
  onSaved?: () => void;
};

const LiveSessionEditor = ({ lessonId, initial, onSaved }: Props) => {
  const { t } = useTranslation();
  const form = useLiveSessionForm({ lessonId, initial, onSaved });

  return (
    <Card className="border-dashed">
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-base">
          <Video className="h-4 w-4" />
          {t('courses.liveSession.title')}
        </CardTitle>
        <CardDescription>
          {t('courses.liveSession.description', {
            timezone: defaultTimezone()
          })}
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="live-meeting-url">
            {t('courses.liveSession.urlLabel')}
          </Label>
          {form.manualEntry ? (
            <>
              <Input
                id="live-meeting-url"
                dir="ltr"
                value={form.meetingUrl}
                onChange={(e) => form.setMeetingUrl(e.target.value)}
                placeholder="https://meet.google.com/..."
              />
              {form.meetingUrl ? (
                <Button
                  type="button"
                  variant="link"
                  className="h-auto p-0 text-xs"
                  onClick={() => form.setManualEntry(false)}
                >
                  {t('courses.liveSession.useGeneratedLink')}
                </Button>
              ) : null}
            </>
          ) : form.meetingUrl ? (
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Input
                  id="live-meeting-url"
                  dir="ltr"
                  readOnly
                  value={form.meetingUrl}
                />
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={() => {
                    navigator.clipboard.writeText(form.meetingUrl);
                    toast.success(t('courses.liveSession.linkCopied'));
                  }}
                  title={t('courses.liveSession.copyLink')}
                >
                  <Copy className="h-4 w-4" />
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={form.regenerate}
                  disabled={form.saving}
                  title={t('courses.liveSession.regenerateLink')}
                >
                  <RefreshCw className="h-4 w-4" />
                </Button>
              </div>
              <div className="flex items-center justify-between text-xs text-muted-foreground">
                <span>{t('courses.liveSession.autoGenerated')}</span>
                <Button
                  type="button"
                  variant="link"
                  className="h-auto p-0 text-xs"
                  onClick={() => form.setManualEntry(true)}
                >
                  {t('courses.liveSession.useOwnLink')}
                </Button>
              </div>
            </div>
          ) : (
            <div className="space-y-2">
              <Button
                type="button"
                variant="secondary"
                onClick={() => form.save()}
                disabled={form.saving}
              >
                {form.saving
                  ? t('courses.liveSession.generating')
                  : t('courses.liveSession.generateLink')}
              </Button>
              <div>
                <Button
                  type="button"
                  variant="link"
                  className="h-auto p-0 text-xs"
                  onClick={() => form.setManualEntry(true)}
                >
                  {t('courses.liveSession.useOwnLink')}
                </Button>
              </div>
            </div>
          )}
        </div>
        <div className="space-y-2">
          <Label htmlFor="live-label">
            {t('courses.liveSession.labelLabel')}
          </Label>
          <Input
            id="live-label"
            value={form.label}
            onChange={(e) => form.setLabel(e.target.value)}
            placeholder={t('courses.liveSession.labelPlaceholder')}
          />
        </div>
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-2">
            <Label htmlFor="live-starts">
              {t('courses.liveSession.startsLabel')}{' '}
              <span className="text-destructive">*</span>
            </Label>
            <DatePicker
              id="live-starts"
              value={form.startsAt}
              onChange={(pickedValue: string) => form.setStartsAt(pickedValue)}
              withTime
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="live-duration">
              {t('courses.liveSession.durationLabel')}{' '}
              <span className="text-destructive">*</span>
            </Label>
            <NumberInput
              id="live-duration"
              value={form.durationMinutes}
              onChange={(raw) => form.setDurationMinutes(raw)}
            />
          </div>
        </div>
        <LiveSessionRecurrence
          repeats={form.repeats}
          days={form.repeatDays}
          until={form.repeatUntil}
          onRepeatsChange={form.enableRepeats}
          onDaysChange={form.setRepeatDays}
          onUntilChange={form.setRepeatUntil}
        />
        <div className="flex flex-wrap gap-2">
          {form.manualEntry || form.meetingUrl ? (
            <Button
              type="button"
              onClick={() => form.save()}
              disabled={form.saving}
            >
              {form.saving ? t('common.saving') : t('courses.liveSession.save')}
            </Button>
          ) : null}
          {initial?.id ? (
            <Button
              type="button"
              variant="outline"
              onClick={form.remove}
              disabled={form.removing}
            >
              {form.removing
                ? t('courses.liveSession.removing')
                : t('courses.liveSession.remove')}
            </Button>
          ) : null}
        </div>
      </CardContent>
    </Card>
  );
};

export default LiveSessionEditor;
