/**
 * GENERATED by Backend/tools/build-log-catalog.mjs — run `pnpm log:catalog` after
 * adding a log call. Descriptions are hand-written and preserved across runs;
 * the event/action/field lists are derived from the code and must not be edited
 * by hand. This file is the single index of every log this app can emit.
 */
import type { LogCatalog } from './logger';

export const LOG_CATALOG = {
  Gdpr: {
    description: 'Cookie and privacy consent captured in the browser.',
    actions: {
      ConsentAccepted: {
        description: 'GDPR consent accepted.',
        status: 'ok',
        fields: ['surface'] as const
      },
      ConsentDeclined: {
        description: 'GDPR consent declined.',
        status: 'ok',
        fields: ['surface'] as const
      }
    }
  },
  Media: {
    description: 'Video and file storage, transcoding and secure playback.',
    actions: {
      PlaybackSessionFailed: {
        description: 'Media playback session failed.',
        status: 'error',
        fields: ['error_name', 'video_id'] as const
      },
      PlayerError: {
        description: 'Media player error.',
        status: 'error',
        fields: ['error_details', 'error_type', 'video_id'] as const
      }
    }
  },
  Onboarding: {
    description: 'First-run setup steps a manager completes to go live.',
    actions: {
      AcademyDialogShown: {
        description: 'TODO: describe this event',
        status: 'ok',
        fields: [] as const
      },
      FirstAcademyCreated: {
        description: 'TODO: describe this event',
        status: 'ok',
        fields: ['academy_id'] as const
      }
    }
  }
} as const satisfies LogCatalog;

export type AppLogCatalog = typeof LOG_CATALOG;
