'use client';

import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { DataPanel } from '@/components/shared/data-list/data-panel';
import { useTranslation } from '@/lib/i18n/hooks';
import { Copy, RefreshCw } from 'lucide-react';
import { toast } from 'react-toastify';
import type { CancelTutoringGroupPayload, TutoringGroup } from '@/types/learning-operations';
import { CancelClassDialog } from './cancel-class-dialog';

type Props = {
  group: TutoringGroup;
  busy: boolean;
  onUpdateLink: (url: string | null, notify: boolean, regenerate?: boolean) => void;
  onAnnounce: (body: string, sendSms: boolean) => void;
  onConfirm: () => void;
  onCancel: (payload: CancelTutoringGroupPayload) => Promise<boolean>;
};

/** Running the class day to day: the link, the announcements, start and stop. */
export const GroupActionsCard = ({
  group,
  busy,
  onUpdateLink,
  onAnnounce,
  onConfirm,
  onCancel,
}: Props) => {
  const { t } = useTranslation();
  const [link, setLink] = useState(group.meeting_url ?? '');
  const [manualEntry, setManualEntry] = useState(
    Boolean(group.meeting_url) && group.meeting_url_source !== 'AUTO_JITSI',
  );
  const [notify, setNotify] = useState(true);
  const [message, setMessage] = useState('');
  const [sendSms, setSendSms] = useState(false);

  useEffect(() => {
    setLink(group.meeting_url ?? '');
    setManualEntry(Boolean(group.meeting_url) && group.meeting_url_source !== 'AUTO_JITSI');
  }, [group.meeting_url, group.meeting_url_source]);

  const canStartNow = group.status === 'WAITING' && group.seats_taken < group.min_students;
  const canCancel = group.status !== 'CANCELLED' && group.status !== 'COMPLETED';

  return (
    <DataPanel
      title={t('tutoring.groups.manageTitle')}
      subtitle={t('tutoring.groups.manageSubtitle')}
    >
      <div className="space-y-6 p-5">
        <div className="space-y-2">
          <Label htmlFor="group-meeting-url">{t('tutoring.groups.meetingUrl')}</Label>
          {manualEntry ? (
            <>
              <Input
                id="group-meeting-url"
                type="url"
                dir="ltr"
                placeholder="https://"
                value={link}
                onChange={(e) => setLink(e.target.value)}
              />
              {link ? (
                <Button
                  type="button"
                  variant="link"
                  className="h-auto p-0 text-xs"
                  onClick={() => setManualEntry(false)}
                >
                  {t('tutoring.groups.useGeneratedLink')}
                </Button>
              ) : null}
            </>
          ) : link ? (
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Input id="group-meeting-url" dir="ltr" readOnly value={link} />
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={() => {
                    navigator.clipboard.writeText(link);
                    toast.success(t('tutoring.groups.linkCopied'));
                  }}
                  title={t('tutoring.groups.copyLink')}
                >
                  <Copy className="h-4 w-4" />
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  disabled={busy}
                  onClick={() => onUpdateLink(null, notify, true)}
                  title={t('tutoring.groups.regenerateLink')}
                >
                  <RefreshCw className="h-4 w-4" />
                </Button>
              </div>
              <div className="flex items-center justify-between text-xs text-muted-foreground">
                <span>{t('tutoring.groups.autoGenerated')}</span>
                <Button
                  type="button"
                  variant="link"
                  className="h-auto p-0 text-xs"
                  onClick={() => setManualEntry(true)}
                >
                  {t('tutoring.groups.useOwnLink')}
                </Button>
              </div>
            </div>
          ) : (
            <div>
              <Button
                type="button"
                size="sm"
                variant="secondary"
                disabled={busy}
                onClick={() => onUpdateLink(null, notify)}
              >
                {busy ? t('tutoring.groups.generating') : t('tutoring.groups.generateLink')}
              </Button>
              <div>
                <Button
                  type="button"
                  variant="link"
                  className="h-auto p-0 text-xs"
                  onClick={() => setManualEntry(true)}
                >
                  {t('tutoring.groups.useOwnLink')}
                </Button>
              </div>
            </div>
          )}
          <div className="flex items-center gap-2">
            <Switch id="group-link-notify" checked={notify} onCheckedChange={setNotify} />
            <Label htmlFor="group-link-notify" className="text-sm font-normal">
              {t('tutoring.groups.notifyOnLinkChange')}
            </Label>
          </div>
          {manualEntry ? (
            <Button
              size="sm"
              disabled={busy || !link.trim()}
              onClick={() => onUpdateLink(link.trim(), notify)}
            >
              {t('tutoring.groups.saveLink')}
            </Button>
          ) : null}
        </div>

        <div className="space-y-2">
          <Label htmlFor="group-announcement">{t('tutoring.groups.announceLabel')}</Label>
          <Textarea
            id="group-announcement"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
          />
          <div className="flex items-center gap-2">
            <Switch id="group-announce-sms" checked={sendSms} onCheckedChange={setSendSms} />
            <Label htmlFor="group-announce-sms" className="text-sm font-normal">
              {t('tutoring.groups.announceSms')}
            </Label>
          </div>
          <Button
            size="sm"
            disabled={busy || !message.trim()}
            onClick={() => {
              onAnnounce(message.trim(), sendSms);
              setMessage('');
            }}
          >
            {t('tutoring.groups.announceSend')}
          </Button>
        </div>

        {canStartNow ? (
          <div className="space-y-2">
            <p className="text-sm text-muted-foreground">{t('tutoring.groups.startNowHint')}</p>
            <Button size="sm" variant="outline" disabled={busy} onClick={onConfirm}>
              {t('tutoring.groups.startNow')}
            </Button>
          </div>
        ) : null}

        {canCancel ? (
          <CancelClassDialog groupId={group.id} disabled={busy} onConfirm={onCancel} />
        ) : null}
      </div>
    </DataPanel>
  );
};
